# Generated by Django 5.0.3 on 2024-03-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="comment",
            field=models.TextField(default=""),
        ),
    ]
