# Generated by Django 5.0.3 on 2024-03-08 04:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_task_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="comment",
        ),
    ]
